### ISSUE TITLE
add code for münster logo

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/traffic-dynamics#12]
possibly useful: https://github.com/hakimel/reveal.js/issues/1122

**Comment by top-on** [comment]
don't have the current app running on my machine. would need onboarding on what's where

**Comment by top-on** [comment]
just tested if the app runs on my machine.
i guess the ticket refers to the traffic-dynamics-shiny project?
don't have the data with the  project, so this is what I get:
![image](https://user-images.githubusercontent.com/6625253/41191324-0700107c-6bee-11e8-91f7-84a973a0429b.png)

**Comment by top-on** [comment]
maybe the logo should be added somewhere else, altogether? :)

**Comment by silberzwiebel** [comment]
sorry, this is meant for the useR R markdown presentation, not the shiny app (although that's a nice idea, too ;)).
P.S.: could you check your slack?

**Comment by top-on** [comment]
added logo to the presentation ;-)
