### ISSUE TITLE
visualize weather (rain, temperature)

### ISSUE THREAD

**Issue by silberzwiebel** [codeformuenster/traffic-dynamics#9]
Depends on having done #3 first.

Then, weather features could be toggable like time features for time series plots (rain: yes / no; temperature: slider like for hours, i.e., warmer / colder than ...), something rather quick then for #6 

This issue is for more / different plots that visualize aggregated weather features (e.g., on how many days was it raining during commuting times?)

**Comment by JokovonJosbach** [comment]
![regenpendlerdiagramm](https://user-images.githubusercontent.com/35098922/34559985-6191247e-f144-11e7-8808-5aab67fdf3bc.JPG)

**Comment by JokovonJosbach** [comment]
Definierren: weiviele Arbeitstage hatte 2017
Definieren: Welche Niederschlagsmengen sind "trocken", "Niesel", "Regen", "Schnee"
Definieren: Pendlerzeiträume (6:30-9:00 und 16:00-18:00 ?)
Daten zusammenlegen und Diagramm erstellen
Prozentual oder absolut (was ist sinnvoller?) angeben, welches Wetter an wievielen Tagen zu den Pendlerzeiten war. Mythos/AUsgangshypothese "Ich kann nicht mit dem Rad zur arbeit fahren, da wird mann nass"

**Comment by silberzwiebel** [comment]
alternative visualisation idea, instead of "false claims" this should be "nass geworden" (thanks to Achim):
![screenshot_20180105-192504](https://user-images.githubusercontent.com/4533862/34641059-6d678840-f2fe-11e7-9c92-c62ed1737570.png)

**Comment by silberzwiebel** [comment]
Done in https://github.com/codeformuenster/traffic-dynamics-shiny/blob/master/shinyapp/calendar_plot.R
see https://twitter.com/codeformuenster/status/993948812707328000
Potentially ending up in the webapp (as interactive feature). Let's see.
For more concrete use cases please open a new issue.
